### ISSUE TITLE
Build failure ("fatal error: pointer-constraints-unstable-v1-client-protocol.h: No such file or directory")

### ISSUE THREAD

**Issue by frutas-fruit** [0xc0de/AngieEngine#3] opened 2022-02-07 16:07 UTC
Hi @0xc0de 

I've tried building on another distro, and I'm getting these errors:
```
/home/..../Downloads/Hork-Source/Source/ThirdParty/SDL2/src/video/wayland/SDL_waylandevents.c:41:10: fatal error: pointer-constraints-unstable-v1-client-protocol.h: No such file or directory
   41 | #include "pointer-constraints-unstable-v1-client-protocol.h"

```
And
```
compilation terminated.
make[2]: *** [Source/ThirdParty/SDL2/CMakeFiles/SDL2-static.dir/build.make:2008: Source/ThirdParty/SDL2/CMakeFiles/SDL2-static.dir/src/video/wayland/SDL_waylandvideo.c.o] Error 1
/home/..../Downloads/Hork-Source/Source/ThirdParty/SDL2/src/video/wayland/SDL_waylandopengles.c:33:10: fatal error: xdg-shell-client-protocol.h: No such file or directory
   33 | #include "xdg-shell-client-protocol.h"

```
Additional Info:

- I've tried building on both an X11 distro (manjaro) and Wayland (garuda), and both fail
- GCC/G++ 11 compiler

How can I solve this? Am I missing special configs or dependencies?

**Comment by 0xc0de** [comment] 2022-02-07 21:49
Hi

I mainly develop on Windows. Visual Studio is my main development environment. I sometimes check the build under Linux, but not regularly, so compilation errors under GCC may occur from time to time. As for Wayland - I have no idea what the problem is yet. Most likely, something needs to be fixed in CMakeLists.txt of the SDL library.

**Comment by 0xc0de** [comment] 2022-02-07 22:15
I just added the missing .xml files that are part of the SDL assembly (wayland protocols). Please update and let me know if the issue is resolved.

**Comment by tree786isback** [comment] 2022-02-07 22:15
Hi
Ok thanks for the info.
>I sometimes check the build under Linux
>
Do you happen to know the last commit you compiled which worked on your linux distro (the commit hash)? I'd like to see if I can build that commit hash if possible . Thanks

**Comment by tree786isback** [comment] 2022-02-07 22:15
>I just added the missing .xml files that are part of the SDL assembly (wayland protocols). Please update and let me know if the >issue is resolved.
Thanks, sure I'll try it again and let you know of the outcome

**Comment by tree786isback** [comment] 2022-02-07 22:24
I've now cloned it and tried building on my Wayland distro (garuda wayfire), and it still seems to be giving errors :
```
[ 70%] Building C object Source/ThirdParty/SDL2/CMakeFiles/SDL2-static.dir/src/core/unix/SDL_poll.c.o
[ 70%] Built target BulletInverseDynamics
/home/..../Hork-Source/Source/ThirdParty/SDL2/src/video/wayland/SDL_waylandevents.c:44:10: fatal error: xdg-shell-unstable-v6-client-protocol.h: No such file or directory
   44 | #include "xdg-shell-unstable-v6-client-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
It repeats that error message a few more times as well

**Comment by 0xc0de** [comment] 2022-02-08 09:46
Try to update submodule:   git submodule update --remote

**Closed as completed** 2022-12-26 18:17 UTC
Labels: bug, help wanted
